### ISSUE TITLE
Update serial library

### ISSUE THREAD

**Issue by airgo-ai** [blues/note-python#34]
The current version of Periphery.Serial does not support Serial.readline so the samples that use this library cannot read from the notecard device.

See line 126 in notecard.py

**Comment by bsatrom** [comment]
Thanks for the report @airgo-ai, I will take a look.

**Comment by bsatrom** [comment]
Hi @airgo-ai upon further review, moving to periphery 2.3.0 is going to be a non-trivial change as we will need to re-instrument our tests and mocks and do some manual testing across platforms. I do want to do this, but don't have a timeline as to when we will be able to. In the meantime, I suggest using the dependencies detailed in requirements.txt, including `2.0.1` for periphery. If you have another version of periphery already installed, you can use a virtual env to target 2.0.1 just to your Notecard project.

**Comment by airgo-ai** [comment]
Ok, thanks.

jz

**Comment by bsatrom** [comment]
Hey @airgo-ai just a heads up. I've refactored the library to utilize PySerial instead of Periphery for Serial-based communications in Linux or on a desktop. Periphery is still used for I2C and has been updated to use 2.3.0.

**Comment by airgo-ai** [comment]
Thanks. I’ll try it this weekend. We’ve been using i2c.

jz
