### ISSUE TITLE
OS can return new-line characters in "sys.version" request, causing JSON parsing issues on Notecard

### ISSUE THREAD

**Issue by gwolffblues** [blues/note-python#47]
In certain circumstances, in the note-python library, the OS is queried and included in a JSON request to Notecard.  If the string returned by the OS includes a new line character "\n", this causes a request parsing error if this string is included in a JSON request sent to Notecard.

 The Notecard uses "\n" characters to delineate the completion of a JSON request.  Since the "\n" appears amid the JSON request, when the Notecard receives it, the JSON is actually incomplete and will result in a parsing error.

For example:

https://github.com/blues/note-python/blob/0896b9a596713febf3ea052ec5d60f74fd092dfc/notecard/notecard.py#L195

can return 

```
3.7.3 (default, Jan 22 2021, 20:04:44) \n[GCC 8.3.0]
```

It appears this \n may be causing a parsing error when a JSON request sent to Notecard including the above string.

### Acceptance Criteria:
```
Given the note-python library queries OS information
  And the OS information strings will be included in a Notecard JSON request
Then the OS information strings are cleaned to remove all new line characters (\r, \n)
  And do not cause JSON parsing errors when strings are included in a Notecard request
```

Log for reproduction steps:
```
pi@raspberrypi:~/example $ python3 rpi-example.py
Opening port...
Opening Notecard...
{"req": "hub.set", "product": "com.xxxxx.xxxxxxxxxxxx:xxxxx_xxxxxxx", "mode": "continuous", "agent": "note-python", "os_name": "cpython", "os_platform": "linux", "os_version": "3.7.3 (default, Jan 22 2021, 20:04:44) \n[GCC 8.3.0]", "req_interface": "i2c", "req_port": 0, "os_family": "posix"}
{"err":"cannot process request: unrecognized: \"req_port\": 0, \"os_family\": \"posix..."}
```

**Comment by bsatrom** [comment]
Thanks @gwolffblues, I will create a test to verify and fix this tomorrow.

**Comment by bsatrom** [comment]
@gwolffblues did you repro this and if so, what Notecard firmware version did you use? I tried to repro this issue on my Pi with a Notecard running 1.5.4 and did *not* get an error.

```
Opening port...
Opening Notecard...
{"req": "hub.set", "product": "com.your-company.your-project", "mode": "continuous", "agent": "note-python", "os_name": "cpython", "os_platform": "linux", "os_version": "3.7.3 (default, Jan 22 2021, 20:04:44) \n[GCC 8.3.0]", "req_interface": "i2c", "req_port": 0, "os_family": "posix"}
{}
{"req": "card.temp"}
{"value":38.25,"calibration":-1.0}
{"req": "card.voltage"}
{"minutes":148,"hours":3,"mode":"normal","value":4.9049517531036273,"vmin":5.0599999999999993,"vmax":5.11,"vavg":5.0933333333333328}
{"req": "card.version"}
{"body":{"org":"Blues Wireless","product":"Notecard","version":"notecard-1.5.4","ver_major":1,"ver_minor":5,"ver_patch":4,"ver_build":12766,"built":"Apr 15 2021 17:48:46"},"version":"notecard-1.5.4.12766","device":"dev:864475044220688","name":"Blues Wireless Notecard","sku":"NOTE-NBGL500","board":"1.11"}
{"req": "note.add", "sync": true, "body": {"temp": 38.25, "voltage": 4.904951753103627}}
```

I seem to remember a Notecard feature at some point that sanitized newlines from all strings...

**Comment by bsatrom** [comment]
FWIW @gwolffblues, I updated my Notecard to LTS (2.1.1) and still cannot repro this issue.

**Comment by gwolffblues** [comment]
@bsatrom I haven't attempted repro.  Given when the Notecard was purchased, I'm assuming it is on build 12200.  I'm awaiting confirmation.

**Comment by gwolffblues** [comment]
@bsatrom Looks like the issue occurs using serial versus I2C.

**Comment by gwolffblues** [comment]
This may actually be the I2C bug in Notecard firmware build 12200.  Recommending a firmware upgrade.  If that doesn't solve the issue I will re-open
