### ISSUE TITLE
importing hub in circuitpython results in an Attribute error

### ISSUE THREAD

**Issue by benlhy** [blues/note-python#48]
**Describe the bug**
Running `from notecard import hub` results in an Attribute error being generated:
```
code.py output:
Traceback (most recent call last):
  File "code.py", line 7, in <module>
  File "/lib/notecard/hub.py", line 20, in <module>
  File "/lib/notecard/validators.py", line 15, in validate_card_object
AttributeError: 'module' object has no attribute 'wraps'

```

**To Reproduce**
1. Add `from notecard import hub` in a device running circuitpython
2. Run the code by pressing `Ctrl-D`
3. The error is generated

**Expected behavior**
Expected import without errors. Importing `notecard` by itself does not cause any errors since it does not use the validator.

**Device (please complete the following information):**
 - CircuitPython Version: 7.1.1
 - Device: Feather nRF52840 Express
 - note-python Version: 1.4.3

**Comment by bsatrom** [comment]
Thanks @benlhy, I will take a look!

**Comment by bsatrom** [comment]
Hey @benlhy was just able to repro this (sorry for the delay) and the issue appears to be that `functools` is not available with CircuitPython. We use `wraps` to ensure that the card instance passed in is an actual Notecard object, but if this isn't possible in CPy, I can figure out a workaround.

In the meantime, using the non-fluent Notecard APIs will work fine with CircuitPython.

**Comment by benlhy** [comment]
Gotcha! For now I just disabled the check and manually made sure that I am
always passing in the right object.

**Comment by bsatrom** [comment]
Hey @benlhy, this is fixed in main. I tested on one of my nRF Feathers, but please do let me know if you have any issues!
